### ISSUE TITLE
Getting the Backend API endpoints working

### ISSUE THREAD

**Issue by sherpa2025** [sherpa2025/Capstone#7]
**Progress:** 
- User signUp and signIn with the JWT token is completed and working both in backend and frontend
- When a JWT token is sent to an backend API endpoints, we get a expected message created in the controller for both Admin and User. 

**ToDO:**
1. Make sure all the logic of API endpoints for all entities is correct/reasonable. (Done)
2. Since user API is done, move to add photo category first with the API endpoints. 
3. Test Photo/Product creation API endpoints. 
4. Order and Cart API endpoint testing simultaneously.

**Comment by sherpa2025** [comment]
Update on 3/25/2024: 
**Backend updated code is in my repo branch: backend-development**

1. Logic for all entities API endpoints is written with the role based validation. 
2. Started testing the Category creation API endpoints as a ADMIN(Role) but got an error with this message: 
         io.jsonwebtoken.io.DecodingException: Illegal base64url character: ' '
        at io.jsonwebtoken.io.Base64.ctoi(Base64.java:221) ~[jjwt-api-0.11.5.jar:0.11.5]
        at io.jsonwebtoken.io.Base64.decodeFast(Base64.java:270) ~[jjwt-api-0.11.5.jar:0.11.5]
 -> Since my User API endpoint is working with the same logic and token, I'm bit confused on this issue. I plan to look into this error on 3/26/2024.
